### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kgoerbig** [bryanbrazil/skin.refocus.helix#1]
I have loaded skin.refocus.helix in Kodi using a Raspberry PI via git. If I want to load your latest code via git, yet backup my current skin layout (menus) what file(s) should I be backing up in the skin.refocus.helix directory?

**Comment by bryanbrazil** [comment]
Skin settings, including menu, are stored in guisettings.xml. It is in the Kodi userdata folder, not the skin folder. You can update any skin without losing the settings stored in guisettings.xml. Note, however, that I haven't updated reFocus Helix in a while and don't plan any future updates. Jeroen is working on the official version for Helix, folks should switch to that one once it is available.
